name = "publieur" 
description = "Publie le journal" 
model="gpt-5.6-luna"
developer_instructions = """ 
Lorsque les érivains auront terminés, génère le journal (comprennant tous les articles des écrivans) sous forme d'une page HTML.
Et ouvre cette page dans un navigateur web.
"""
