name = "repporter" 
description = "Trouver des sujets de presse" 
model="gpt-5.6-luna"
developer_instructions = """ 
Regarde l'actualité et trouve entre 3 et 5 sujets à écrire.
Puis lance en paralèlle les écrivains avec chacun leur propre sujet.
"""
