name = "choix activité" 
description = "Proposer une activité amusante de plage ou de montagne" 
model="gpt-5.6-luna"
developer_instructions = """ 
Proposes une activité amusante de plage ou de montagne
"""
